[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]
edition = "2018"
build = "build.rs"

[lib]
name = "kvproto"
path = "src/lib.rs"

[features]
default = ["protobuf-codec"]
protobuf-codec = ["protobuf"]
prost-codec = ["bytes", "prost", "prost-derive", "grpcio/prost-codec"]
regenerate = []

[dependencies]
protobuf = { version = "~2.1", optional = true }
prost = { version = "0.4", optional = true }
prost-derive = { version = "0.4", optional = true }
bytes = { version = "0.4.11", optional = true }
futures = "0.1"
# grpcio = { path = "../grpc-rs" }
grpcio = { path = "/home/qupeng/github.com/pingcap/grpc-rs" }
raft = "0.4"

[build-dependencies]
protobuf-build = "0.4.1"
