[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]
edition = "2018"
build = "build.rs"

[lib]
name = "kvproto"
path = "src/lib.rs"

[features]
default = ["prost-codec"]
prost-codec = ["bytes", "prost", "prost-derive", "grpcio/prost-codec"]
regenerate = []

[dependencies]
protobuf = { version = "~2.1" }
prost = { version = "0.5", optional = true }
prost-derive = { version = "0.5", optional = true }
bytes = { version = "0.4.11", optional = true }
futures = "0.1"
lazy_static = { version = "1.3" }
grpcio = "0.5.0-alpha.1"
# raft = "0.4"
raft = { git = "https://github.com/hicqu/raft-rs", branch = "cc-effective-on-received" }

[build-dependencies]
protobuf-build = "0.4.1"
